### ISSUE TITLE
Shiny App does not load when wrapped with profvis({})

### ISSUE THREAD

**Issue by khoulih** [rstudio/profvis#106]
I have a shiny app that is getting pretty lengthy. As a result, I would like to profile the app to find areas for optimization.
Running the `runApp("file/path")` function loads the app perfectly. However, when I wrap the function with `profvis({})` like so; `profvis({runApp("file/path")})` the browser for the app will pop up, however the rest of the app does not render. I tried running this in RStudio as well, but to no avail. In fact, the RStudio session explicitly crashes when I try to profile the app. 
Below is my session info, if that helps.

`
> session_info()
- Session info ---------------------------------------------------------------
 setting  value
 version  R version 3.5.3 (2019-03-11)
 os       Windows 10 x64
 system   x86_64, mingw32
 ui       RTerm
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/New_York
 date     2019-04-25

- Packages -------------------------------------------------------------------
 package        * version    date       lib source
 assertthat       0.2.1      2019-03-21 [1] CRAN (R 3.5.3)
 backports        1.1.4      2019-04-10 [1] CRAN (R 3.5.3)
 bitops         * 1.0-6      2013-08-17 [1] CRAN (R 3.5.2)
 broom            0.5.2      2019-04-07 [1] CRAN (R 3.5.3)
 callr            3.2.0      2019-03-15 [1] CRAN (R 3.5.3)
 cellranger       1.1.0      2016-07-27 [1] CRAN (R 3.5.2)
 cli              1.1.0      2019-03-19 [1] CRAN (R 3.5.3)
 colorspace       1.4-1      2019-03-18 [1] CRAN (R 3.5.3)
 crayon           1.3.4      2017-09-16 [1] CRAN (R 3.5.2)
 crosstalk        1.0.0      2016-12-21 [1] CRAN (R 3.5.2)
 curl             3.3        2019-01-10 [1] CRAN (R 3.5.2)
 data.table     * 1.12.2     2019-04-07 [1] CRAN (R 3.5.3)
 desc             1.2.0      2018-05-01 [1] CRAN (R 3.5.2)
 devtools       * 2.0.2      2019-04-08 [1] CRAN (R 3.5.3)
 digest           0.6.18     2018-10-10 [1] CRAN (R 3.5.2)
 dplyr          * 0.8.0.1    2019-02-15 [1] CRAN (R 3.5.2)
 DT             * 0.5        2018-11-05 [1] CRAN (R 3.5.2)
 edgarWebR      * 1.0.0      2018-05-25 [1] CRAN (R 3.5.3)
 feedeR         * 0.0.7      2016-10-25 [1] CRAN (R 3.5.2)
 forcats        * 0.4.0      2019-02-17 [1] CRAN (R 3.5.2)
 fs               1.2.7      2019-03-19 [1] CRAN (R 3.5.3)
 generics         0.0.2      2018-11-29 [1] CRAN (R 3.5.2)
 ggplot2        * 3.1.1      2019-04-07 [1] CRAN (R 3.5.3)
 ggthemes       * 4.1.1      2019-04-09 [1] CRAN (R 3.5.3)
 glue             1.3.1      2019-03-12 [1] CRAN (R 3.5.3)
 gtable           0.3.0      2019-03-25 [1] CRAN (R 3.5.3)
 haven            2.1.0      2019-02-19 [1] CRAN (R 3.5.2)
 hms              0.4.2      2018-03-10 [1] CRAN (R 3.5.2)
 htmltools        0.3.6      2017-04-28 [1] CRAN (R 3.5.2)
 htmlwidgets      1.3        2018-09-30 [1] CRAN (R 3.5.2)
 httpuv           1.5.1      2019-04-05 [1] CRAN (R 3.5.3)
 httr             1.4.0      2018-12-11 [1] CRAN (R 3.5.2)
 jsonlite         1.6        2018-12-07 [1] CRAN (R 3.5.2)
 later            0.8.0      2019-02-11 [1] CRAN (R 3.5.2)
 lattice          0.20-38    2018-11-04 [1] CRAN (R 3.5.3)
 lazyeval         0.2.2      2019-03-15 [1] CRAN (R 3.5.3)
 lubridate        1.7.4      2018-04-11 [1] CRAN (R 3.5.2)
 magrittr         1.5        2014-11-22 [1] CRAN (R 3.5.2)
 markdown       * 0.9        2018-12-07 [1] CRAN (R 3.5.2)
 memoise          1.1.0      2017-04-21 [1] CRAN (R 3.5.2)
 mime             0.6        2018-10-05 [1] CRAN (R 3.5.2)
 modelr           0.1.4      2019-02-18 [1] CRAN (R 3.5.2)
 munsell          0.5.0      2018-06-12 [1] CRAN (R 3.5.2)
 nlme             3.1-137    2018-04-07 [1] CRAN (R 3.5.3)
 openxlsx       * 4.1.0      2018-05-26 [1] CRAN (R 3.5.2)
 pillar           1.3.1.9000 2019-02-04 [1] Github (r-lib/pillar@3a54b8d)
 pkgbuild         1.0.3      2019-03-20 [1] CRAN (R 3.5.3)
 pkgconfig        2.0.2      2018-08-16 [1] CRAN (R 3.5.2)
 pkgload          1.0.2      2018-10-29 [1] CRAN (R 3.5.2)
 plotly         * 4.9.0      2019-04-10 [1] CRAN (R 3.5.3)
 plyr           * 1.8.4      2016-06-08 [1] CRAN (R 3.5.2)
 prettyunits      1.0.2      2015-07-13 [1] CRAN (R 3.5.2)
 processx         3.3.0      2019-03-10 [1] CRAN (R 3.5.3)
 profvis        * 0.3.5      2018-02-22 [1] CRAN (R 3.5.3)
 promises         1.0.1      2018-04-13 [1] CRAN (R 3.5.2)
 ps               1.3.0      2018-12-21 [1] CRAN (R 3.5.2)
 purrr          * 0.3.2      2019-03-15 [1] CRAN (R 3.5.3)
 quantmod       * 0.4-14     2019-03-24 [1] CRAN (R 3.5.3)
 R6               2.4.0      2019-02-14 [1] CRAN (R 3.5.2)
 RColorBrewer   * 1.1-2      2014-12-07 [1] CRAN (R 3.5.2)
 Rcpp             1.0.1      2019-03-17 [1] CRAN (R 3.5.3)
 RCurl          * 1.95-4.12  2019-03-04 [1] CRAN (R 3.5.2)
 readr          * 1.3.1      2018-12-21 [1] CRAN (R 3.5.2)
 readstata13    * 0.9.2      2018-05-26 [1] CRAN (R 3.5.2)
 readxl           1.3.1      2019-03-13 [1] CRAN (R 3.5.3)
 remotes          2.0.4      2019-04-10 [1] CRAN (R 3.5.3)
 reshape2       * 1.4.3      2017-12-11 [1] CRAN (R 3.5.2)
 rlang            0.3.4      2019-04-07 [1] CRAN (R 3.5.3)
 rprojroot        1.3-2      2018-01-03 [1] CRAN (R 3.5.2)
 rstudioapi       0.10       2019-03-19 [1] CRAN (R 3.5.3)
 rvest            0.3.3      2019-04-11 [1] CRAN (R 3.5.3)
 scales           1.0.0      2018-08-09 [1] CRAN (R 3.5.2)
 sessioninfo      1.1.1      2018-11-05 [1] CRAN (R 3.5.2)
 shiny          * 1.3.0      2019-04-07 [1] CRAN (R 3.5.3)
 shinyBS        * 0.61       2015-03-31 [1] CRAN (R 3.5.2)
 shinydashboard * 0.7.1      2018-10-17 [1] CRAN (R 3.5.2)
 shinyjs        * 1.0        2018-01-08 [1] CRAN (R 3.5.2)
 shinyLP        * 1.1.2      2018-04-25 [1] CRAN (R 3.5.2)
 shinythemes    * 1.1.2      2018-11-06 [1] CRAN (R 3.5.2)
 shinyWidgets   * 0.4.8      2019-03-18 [1] CRAN (R 3.5.3)
 stringi          1.4.3      2019-03-12 [1] CRAN (R 3.5.3)
 stringr        * 1.4.0      2019-02-10 [1] CRAN (R 3.5.2)
 testthat         2.0.1      2018-10-13 [1] CRAN (R 3.5.2)
 tibble         * 2.1.1      2019-03-16 [1] CRAN (R 3.5.3)
 tidyr          * 0.8.3      2019-03-01 [1] CRAN (R 3.5.2)
 tidyselect       0.2.5      2018-10-11 [1] CRAN (R 3.5.2)
 tidyverse      * 1.2.1      2017-11-14 [1] CRAN (R 3.5.2)
 TTR            * 0.23-4     2018-09-20 [1] CRAN (R 3.5.2)
 usethis        * 1.5.0      2019-04-07 [1] CRAN (R 3.5.3)
 viridisLite      0.3.0      2018-02-01 [1] CRAN (R 3.5.2)
 withr            2.1.2      2018-03-15 [1] CRAN (R 3.5.2)
 XML              3.98-1.19  2019-03-06 [1] CRAN (R 3.5.2)
 xml2           * 1.2.0      2018-01-24 [1] CRAN (R 3.5.3)
 xtable           1.8-3      2018-08-29 [1] CRAN (R 3.5.2)
 xts            * 0.11-2     2018-11-05 [1] CRAN (R 3.5.2)
 yaml             2.2.0      2018-07-25 [1] CRAN (R 3.5.2)
 zip              2.0.1      2019-03-11 [1] CRAN (R 3.5.3)
 zoo            * 1.8-5      2019-03-21 [1] CRAN (R 3.5.3)

[1] C:/Users/khoulih/Documents/R/R-3.5.3/library
`

Any help on this matter would be extremely appreciated. 

Thanks in advance.

**Comment by sanjmeh** [comment]
any progress on this one?

**Comment by chasemc** [comment]
Try increasing the `internal` argument for `profvis::profvis()

**Comment by augustohassel** [comment]
> Try increasing the `interval` argument for `profvis::profvis()

that worked form me!

**Comment by hadley** [comment]
This worked fine for me:

```R
library(shiny)

ui <- fluidPage(
  sliderInput("x", "x", 0, 9, 1),
  plotOutput("plot")
)

server <- function(input, output, session) {
  x <- reactive(runif(0, 1, n = 10 ^ input$x))
  output$plot <- renderPlot({
    hist(x())
  })
}

profvis::profvis(
  runApp(shinyApp(ui, server))
)
```

So it don't think it's a general issue with profvis.

**Comment by beansrowning** [comment]
Just to come to this issue from the future, this seems this is still a problem. increasing the `interval` argument did help, but it's unclear why this is happening in the first place.

My RStudio session gets so hung up that I have to force quit from task manager if I try to profile my shiny app without increasing the interval.
