### ISSUE TITLE
Cannot access memory alloc/dealloc values from profvis object 

### ISSUE THREAD

**Issue by cakirb** [rstudio/profvis#112]
Sometimes HTML files produced by profvis can be quite big, and they cannot be opened. When I wanted to check memory values (total memory alloc/dealloc values of the function) from profvis object, I saw these values cannot be accessed from there. I checked the JS script of profvis and I am confused about how these values were calculated. How can I reproduce these values in a memory-efficient way? There should be an easy way to access those values without dealing with huge R objects or HTML files.

**Comment by wch** [comment]
IIRC, the allocation/deallocation information for a given line of code is computed when the HTML file is loaded in the browser.

If you want to compute it separately, you could run `Rprof()` and parse the data yourself. There are other packages for working with data from Rprof which may do what you want.
