### ISSUE TITLE
support chrome profile tool?

### ISSUE THREAD

**Issue by comicfans** [rstudio/profvis#117]
Hello, profvis is very useful for visualize profile information, but I found it became really slow when code gets larger, the viewer web page may spend more than 5 minutes to load and almost not responsive , firefox/chrome both complain this page got too slow and even force kill it , I'd like to know if profvis will port to [chrome trace event format](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit)?   chrome built-in profiler seems handle these profile data really well

**Comment by hadley** [comment]
I think it will be easier to just make profvis faster, rather than switching to a completely different tool.

**Comment by wch** [comment]
You know, I think this is actually worth investigating. The format looks pretty simple, and the Chrome profiler even supports looking at source files (though we may have to do this with source maps or something like that).

Then it would be really fast, and we wouldn't have to maintain or optimize the GUI code at all.

![Screen Recording 2020-11-17 at 10 06 07 AM 2020-11-17 10_07_42](https://user-images.githubusercontent.com/86978/99414982-f982e580-28bc-11eb-82e6-3f1135da937d.gif)

**Comment by hadley** [comment]
But optimising the GUI code should be easy? (once we find the right person). Using chrome profile would require folks to use chrome, and wouldn't be embeddable in the HTML widgets.

**Comment by wch** [comment]
I remember the GUI code was pretty complicated, and I think it would be harder to convert it to canvas than it would be to massage the data into the Chrome profiler format. I bet that a first implementation of data transformation code could be done in a day.

The flame graph + code integration in the existing profvis GUI is pretty nice, though, and we'd lose out on that.

**Comment by comicfans** [comment]
> But optimising the GUI code should be easy? (once we find the right person). Using chrome profile would require folks to use chrome, and wouldn't be embeddable in the HTML widgets.

chrome built-in profile viewer [is just a embedded html widget](https://chromium.googlesource.com/catapult/+/refs/heads/master/tracing/) , you can easily [create a self-contained html](https://github.com/catapult-project/catapult/blob/master/tracing/docs/embedding-trace-viewer.md) and show it in any browser.  and I don't other person than chrome guys have better html optimization experiences( they're using this viewer to show android/fuchsia system tracing, which has huge events)

**Comment by hadley** [comment]
@comicfans I'm not claiming that we can make something faster than the chrome devs, but I'm pretty sure that we can make something fast enough, and I suspect that correctly embedding the chrome profiler into an R package is going to be a lot of work.

**Comment by wch** [comment]
I'm closing this issue now since we're going to go the route of optimizing the existing profvis code, but it may be worth revisiting this in the future.
