### ISSUE TITLE
Output changes on repeated trials

### ISSUE THREAD

**Issue by TylerGrantSmith** [rstudio/profvis#120]
I run the following code:
```
profvis::profvis(
  {
    x <- runif(1e8)
    y <- runif(1e8)
    z <- c(x, y)
  }
)
```
in a fresh R session, the output is: 
![image](https://user-images.githubusercontent.com/39497067/89599799-250a2480-d826-11ea-8ca9-046036480f9d.png)

if I run the same code again (even after clearing the workspace and forcing a garbage collection), the output is:
![image](https://user-images.githubusercontent.com/39497067/89599853-3b17e500-d826-11ea-9230-fd3c2ac4d4f5.png)

What is happening here on the second iteration?  The first result on the fresh R session is what I would expect to see.

**Comment by wch** [comment]
I'm not really sure exactly why that is -- this sounds like a question for the R-devel mailing list.
