### ISSUE TITLE
Document required version of RStudio

### ISSUE THREAD

**Issue by davidchall** [rstudio/profvis#129]
There are a couple of places in the profvis docs that state the Preview Release of RStudio is required to use the integrated viewer ([here](https://github.com/rstudio/profvis/blob/44b8418896b865a24e278dd84e33cbe5962c123c/docs/rstudio.Rmd#L13) and [here](https://github.com/rstudio/profvis/blob/44b8418896b865a24e278dd84e33cbe5962c123c/docs/index.Rmd#L45)). I think this might not be true anymore (it works in my RStudio 1.4 release). Does anyone know when the profvis integration was released in RStudio?

**Comment by wch** [comment]
Thanks - it's been in RStudio for several years now, so I'll just take out the preview wording.

**Comment by wch** [comment]
Closed by bba3bff
