### ISSUE TITLE
profvis doesn't draw anything

### ISSUE THREAD

**Issue by helske** [rstudio/profvis#15]
I am trying to profile complex optimization problem with `profvis` but when trying to print the output the browser renders the output as blank screen. Same thing with Rstudio's editor. 

I managed to reproduce the problem with this simple code:

```
rm(list = ls())
set.seed(1)
x <- rnorm(10000)

outer_function_with_obj <- function(x){
  obj1 <- function(x) {
    x1 <- x[1]
    x2 <- x[2]
    100 * (x2 - x1 * x1)^2 + (1 - x1)^2
  }
  optim(par = x, fn = obj1)
}
does_not_work <- profvis({
  outer_function_with_obj(x = x)
})

obj2 <- function(x) {
  x1 <- x[1]
  x2 <- x[2]
  100 * (x2 - x1 * x1)^2 + (1 - x1)^2
}
outer_function_without_obj <- function(x){
  optim(par = x, fn = obj2)
}
does_work <- profvis({
  outer_function_without_obj(x = x)
})
```

**Comment by wch** [comment]
Hm, it looks like it happens when a function is defined and called within another function, and that outer function is defined outside of a `profvis()` call. (Moving it inside the `profvis()` makes it work.) For example, this has the same problem:

```R
f1 <- function() {
  g <- function() {
    pause(0.1)
  }
  g()
}
profvis({
  f1()
})


profvis({
  f()
})
```


But these work:

```R
# No inner function
f2 <- function() {
  pause(0.1)
}
profvis({
  f2()
})

# Inner function is returned, then called from inside profvis()
f3 <- function() {
  g <- function() {
    pause(0.1)
  }
  g
}
profvis({
  x <- f3()
  x()
})


# Outer function is defined within profvis()
profvis({
  f4 <- function() {
    g <- function() {
      pause(0.1)
    }
    g()
  }
  f4()
})
```

**Comment by nuno-agostinho** [comment]
+1 I'm also having this problem.

**Comment by wch** [comment]
I have a feeling that it won't be possible to fix this -- the R profiler output simply doesn't contain enough information to retrieve the source code that's outside of the `profvis()` call. So you may just have to put all your code in `profvis()`, or in a file that's `source`d.

**Comment by wch** [comment]
This is fixed now - it simply won't try to display code that's outside of the `profvis({})` call.

Simplified test app for future reference:


```R
library(profvis)
f <- function() {
  # This empty line is needed
  pause(0.1)
}

profvis({ f() })
```

**Comment by xshi0001** [comment]
HI! wch, I think it's not the package problem, it's something related to Rstudio. I use your code,
 `library(profvis)
f <- function() {
    # This empty line is needed
    pause(0.1)
}

profvis({ f() })
`
but the result of the profile screen is nothing
![image](https://user-images.githubusercontent.com/28589533/38169354-c9abc8a8-359a-11e8-8086-b9a6d26d7e06.png)
![image](https://user-images.githubusercontent.com/28589533/38169355-d25e3a76-359a-11e8-87b2-65c361d61565.png)

**Comment by wch** [comment]
@xshi0001 Can you file a new issue? And please include the output of `devtools::session_info()`.

**Comment by hwpvdtoorn** [comment]
Hi, I know this is closed, but I experienced the same thing. Since this is the only place that pops up on Google, I'd like to add, that profvis gives a blank screen when your path contains spaces.

**Comment by hwpvdtoorn** [comment]
Hi, thanks for your reply. I tried to create an example but unfortunately that worked normally, so I can't repeat this.
