### ISSUE TITLE
not sure why this is not working

### ISSUE THREAD

**Issue by KhatriVivek** [rstudio/profvis#21]
profvis({
             x=rnorm(1000000)                                          
             y=rnorm(1000000)
})

After I run code above, I receive the following error:
Error: unexpected symbol in "profvis({x=rnorm(100000)                                          
                                                            y"

I thought this would have worked based on your example:

profvis({
  g <- ggplot(diamonds, aes(carat, price)) + geom_point(size = 1, alpha = 0.2)
  print(g)
})

**Comment by wch** [comment]
Works fine for me. Are you sure you don't have a strange invisible character in there?

**Comment by KhatriVivek** [comment]
So if you copy the code from the issues section/Notepad and paste into
RStudio, then it worked for me.

However, if I write the code in RStudio from scratch, it does not run.

The following does work
(1) write the code in RStudio
(2) copy from RStudio
(3) paste in Notepad
(4) hit return to put each statement on a separate line
(5) copy from Notepad
(6) paste back into R Studio

**Comment by wch** [comment]
I don't think this is a problem with profvis -- I think you probably have some sort of problem with encoding or keyboard input.

If you run this, the error is almost the same, which suggests to me that the newline characters when you type in RStudio are not actually newline characters, though they look like them.


```R
profvis({
x=rnorm(1e6)y=rnorm(1e6)
})
# Error: unexpected symbol in:
# "profvis({
# x = rnorm(1e6)y"
```
