### ISSUE TITLE
Left Code Panel Doesn't Show Up

### ISSUE THREAD

**Issue by feiyangdou** [rstudio/profvis#28]
Hi,

I tried to save the returned object of _profvis()_ and open it later. It turns out that the flamegraph works fine but the code panel in the left doesn't show up as shown in the screenshot. Any idea why it happens? Thanks!

`vis <- profvis({
R Code Here
})`
`htmlwidgets::saveWidget(vis, "file.html")`

![prof_vis_issue](https://cloud.githubusercontent.com/assets/10117194/13375767/6738e1de-dd76-11e5-9d42-0ab7ced97de1.PNG)

**Comment by wch** [comment]
I'm not able to replicate this problem. For example, this works for me.

```R
p <- profvis({
  pause(0.5)
})

htmlwidgets::saveWidget(p, "test.html")
```

Can you provide a reproducible example?

**Comment by feiyangdou** [comment]
Sorry for the late response. I realized that if I run the script in a BATCH mode or using Rscript, then the code panel won't show up. Just wonder if that is something could be fixed. Thanks!

**Comment by wch** [comment]
Ah, you'll need to enable the option `keep.source` in order for R to record the source code when running from Rscript. For example, this should work:

```
Rscript -e "options(keep.source=TRUE); p <- profvis::profvis({ profvis::pause(0.2) }); htmlwidgets::saveWidget(p, 'test.html')"
```

I'll update the FAQ with this information.
