### ISSUE TITLE
failed attempt to install

### ISSUE THREAD

**Issue by rpietro** [rstudio/profvis#29]
Hi, tried to install through github as well as locally, getting an error on both. Not sure what I might be doing wrong. Output and session info below:

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin14.5.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Microsoft R Open 3.2.3
Default CRAN mirror snapshot taken on 2016-01-01
The enhanced R distribution from Microsoft
Visit http://go.microsoft.com/fwlink/?LinkID=722555 for information
about additional features.

Multithreaded BLAS/LAPACK libraries detected. Using 2 cores for math algorithms.
> setwd("~/Desktop/profvis-master")
> require(devtools)
Loading required package: devtools
> install(".")
Installing profvis
Skipping 1 packages ahead of CRAN: digest
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL '/Users/rpietro/Desktop/profvis-master'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘profvis’ ...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -DPLATFORM_PKGTYPE='"mac.binary.mavericks"'    -fPIC  -Wall -mtune=core2 -g -O2  -c pause.c -o pause.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/X11/lib -L/usr/local/lib /usr/local/lib/libcairo.a /usr/local/lib/libpixman-1.a /usr/local/lib/libfreetype.a /usr/local/lib/libfontconfig.a -lxml2 /usr/local/lib/libreadline.a -o profvis.so pause.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
clang: error: no such file or directory: '/usr/local/lib/libreadline.a'
make: *** [profvis.so] Error 1
ERROR: compilation failed for package ‘profvis’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/profvis’
Error: Command failed (1)
> session_info()
Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin14.5.0        
 ui       RStudio (0.99.878)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2016-02-27                  

Packages --------------------------------------------------------------------------------------
 package  * version date       source        
 devtools * 1.9.1   2015-09-11 CRAN (R 3.2.0)
 digest     0.6.9   2016-01-08 CRAN (R 3.2.3)
 knitr      1.12    2016-01-07 CRAN (R 3.2.3)
 memoise    0.2.1   2014-04-22 CRAN (R 3.2.0)
> devtools::install_github("rstudio/profvis")
Downloading GitHub repo rstudio/profvis@master
Installing profvis
Skipping 1 packages ahead of CRAN: digest
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  '/private/var/folders/jr/f1f9y58d4p30zq332mt_367h0000gn/T/Rtmpzf4tz7/devtools19436aafd9c/rstudio-profvis-ce265e5'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘profvis’ ...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -DPLATFORM_PKGTYPE='"mac.binary.mavericks"'    -fPIC  -Wall -mtune=core2 -g -O2  -c pause.c -o pause.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/X11/lib -L/usr/local/lib /usr/local/lib/libcairo.a /usr/local/lib/libpixman-1.a /usr/local/lib/libfreetype.a /usr/local/lib/libfontconfig.a -lxml2 /usr/local/lib/libreadline.a -o profvis.so pause.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
clang: error: no such file or directory: '/usr/local/lib/libreadline.a'
make: *** [profvis.so] Error 1
ERROR: compilation failed for package ‘profvis’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/profvis’
Error: Command failed (1)

**Comment by wch** [comment]
Installing profvis from source requires the ability to compile packages. It looks like you need `libreadline.a`. How you get this on your system is system-specific. I don't for sure, but it's also possible that it might compile correctly with the regular (non-MS) R distribution.

**Comment by wch** [comment]
One more thing: once the package is on CRAN, it won't require compilation because the pre-compiled binary package will be available.
