### ISSUE TITLE
First time clicking on an option has no effect

### ISSUE THREAD

**Issue by wch** [rstudio/profvis#48]
The first time that "Hide lines of code with zero time, "Hide memory results", or "Hide internal function calls" are clicked, nothing happens. A second click is required to select the checkbox. This is in RStudio on a Mac, but probably happens in other browsers as well.

![image](https://cloud.githubusercontent.com/assets/86978/14960766/e461b948-105b-11e6-82d9-b600ae4d8b15.png)

**Comment by javierluraschi** [comment]
@wch I've seen this one as well, made me think I was not clicking on the right place. I'll be happy to take a look, feel free to assign this to me.
