### ISSUE TITLE
Code panel has blank column on right

### ISSUE THREAD

**Issue by wch** [rstudio/profvis#55]
On my Mac, I see a light gray column to the right of the code panel in RStudio, Chrome, Safari, and Firefox:

![image](https://cloud.githubusercontent.com/assets/86978/15003800/53dc52e6-1175-11e6-868f-b3687995f7e6.png)

However, @javierluraschi has reported that he doesn't see it on his machine, even when we're looking at the exact same file.

The file is here:
https://rawgit.com/wch/650826ea13ed012617f98a9b4821db92/raw/5e93063562c0d7e2111eb7a10ddb1bbaafca43ed/profvis.html

To repro in a browser:

```R
p <- profvis({ pause(0.1) })
htmlwidgets::saveWidget(p, "output.html")
browseURL("output.html")
```

**Comment by javierluraschi** [comment]
This is the rendering in my local environment, no repro in safari, nor chrome, nor the IDE. Need to spend more time here finding a local repro...

![correct rendering](https://cloud.githubusercontent.com/assets/3478847/15003886/9fa9f544-1165-11e6-8741-0da1c6eab9ea.png)

**Comment by javierluraschi** [comment]
@dfalty found that it reproed on his system, @jmcphers noticed this might be the "always show scrollbar" option from the mac system options, it was! @wch Checked in fix, this was a really old CSS rule introduced here: https://github.com/rstudio/profvis/commit/7589410da4e18f411856b27d33049b958ef89f5a

**Comment by wch** [comment]
Nice sleuthing, guys!
