### ISSUE TITLE
Profvis produces error: No parsing data available

### ISSUE THREAD

**Issue by vandit15** [rstudio/profvis#75]
When I run this chunk of code
```
library(profvis)
f <- function() {
   
pause(0.1)
}

p<-profvis({ f() })
print(p)
````
I get a profvis profile as an output,
but 
when I run profvis on my code which is as follows:
````
setMethod("plot", signature(x = "markovchain", y = "missing"),
		      function(x, y, package = "igraph", ...) {
		        switch(package,
		         diagram = {
		           if (requireNamespace("diagram", quietly = TRUE)) {
		             .plotdiagram(object = x, ...)
		           } else {
		             netMc <- .getNet(object = x, round = TRUE)
		             edgeLabel <- round(E(netMc)$weight / 100, 2)
		             plot.igraph(x = netMc, edge.label = edgeLabel, ...)
		           }
		         },
		         
		         DiagrammeR = {
		           if (requireNamespace("DiagrammeR", quietly = TRUE)) {
		             .plotDiagrammeR(object = x, ...)
		           } else {
		             netMc <- .getNet(object = x, round = TRUE)
		             edgeLabel <- round(E(netMc)$weight / 100, 2)
		             plot.igraph(x = netMc, edge.label = edgeLabel, ...)
		           }
		         },
		         {
		           netMc <- .getNet(object = x,round = TRUE)
		           edgeLabel <- round(E(netMc)$weight / 100, 2)
		           plot.igraph(x = netMc, edge.label = edgeLabel, ...)
		        })
		}
)
````
````
p<-profvis::profvis({
pause(.1)
plot(mathematicaMc, layout = layout.fruchterman.reingold)
pause(.1)
})
print(p)
````
Here `mathematicaMc` is some object of the required class.
I get the error: 
````
Error in parse_rprof(prof_output, expr_source) : 
  No parsing data available. Maybe your function was too fast?
````
How is this possible? Can someone help?

**Comment by wch** [comment]
If you use the argument `prof_output="output.prof"`, then open output.prof, is there anything in the file?

**Comment by vandit15** [comment]
Sorry for the late response. An output comes in the file `output.prof` which has every line somewhat like this:
````:836859:978675:91813400:2215:"as.list" "mayCallBrowserList" "mayCallBrowser" "mayCallBrowserList" "mayCallBrowser" "mayCallBrowserList" "mayCallBrowser" "cmpfun" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "compiler:::tryCmpfun" "igraph_options" "%in%" "i.parse.plot.params" "plot.igraph" 1#645 "force" "doTryCatch" "tryCatchOne" "tryCatchList" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "profvis::profvis" 1#620 ".local" "plot" "plot" ````

**Comment by wch** [comment]
That's strange. If has that output, then there is data there. Can you provide a reproducible example? I haven't been able to get your code to work.

**Comment by vandit15** [comment]
I suppose you would have to have the R package to run this snippet. Can you please clone the R package from [here](https://github.com/spedygiorgio/markovchain) and build it to run profvis on it. The function (plot) I am talking about can be found [here](https://github.com/spedygiorgio/markovchain/blob/master/R/0_classesAndMethods.R#L618).
You would have to build an object of markovchain class, which can be done using:
````
transMatr<-matrix(c(0.4,0.6,.3,.7),nrow=2,byrow=TRUE)
simpleMc<-new("markovchain", states=c("a","b"),
transitionMatrix=transMatr,name="simpleMc")
````
Then you can run plot function using `plot(simpleMc)`

**Comment by wch** [comment]
Can you supply a reproducible example, ideally something that can be cut and pasted in an R session to reproduce the problem? It would be more efficient if you can supply that, instead of having others try to piece together an example.

**Comment by vandit15** [comment]
Sorry, but there was a confusion, I was not using profvis properly on an R package untill now, hence getting the error. You may close the issue. Thanks for the support.

**Comment by wangxuesong29** [comment]
Hi. I am trying to warp the shiny runApp with profvis, but I meet an error as following:
```
# Run dashboard app on port 8888
require(shiny)
#> Loading required package: shiny
#> Warning: package 'shiny' was built under R version 3.4.2
library(profvis)
#> Warning: package 'profvis' was built under R version 3.4.3
profvis({
  shiny::runApp(
    appDir = dirname(sys.frame(1)$ofile),
    port = 8888,
    launch.browser = FALSE,
    quiet = TRUE)
})
#> profvis: code exited with error:
#> a character vector argument expected
#> Error in parse_rprof(prof_output, expr_source): No parsing data available. Maybe your function was too fast?
```

**My Shiny app is a bit huge, with more than 40 modules, I need to find out which part is taking 10 seconds to run, which is not acceptable. **

**Comment by sanjmeh** [comment]
`profvis()` always gives this error on shinyapps. Not sure if it is designed to work around reactive expressions. If there is anywhere else this problem is reported could someone point me there?

**Comment by subhasish1315** [comment]
I tried a couple of types of test case. I observed  in a new session if we run `profvis()` first before single time running the app it is showing the error. But after running the APP then stopping the app and again running `profvis()` it is   working fine...

in nutshell

Case 1 
Fresh Session--> Run Profvis() --> return error
Case 2
Fresh Session--> Run App--> Stop App--> Run profvis()--> Return result
(you can run profvis multiple times in Case2)

@wch can you take a look on this??
