### ISSUE TITLE
Border is a bit too thick/black when selected

### ISSUE THREAD

**Issue by hadley** [rstudio/profvis#8]
![screen shot 2015-10-19 at 5 37 26 pm](https://cloud.githubusercontent.com/assets/4196/10593301/22d09cee-7688-11e5-8801-d6430e965056.png)

**Comment by wch** [comment]
Some possible solutions:

* Raise the z-index.
* Raise the z-index and add shadow.
* Don't change the stroke width, but do change color.
* Use a CSS filter effect on the rect to indicate that it's locked.

**Comment by wch** [comment]
Fixed in f9e8e37, by moving to front.
