### ISSUE TITLE
Data view fails to display leaf nodes

### ISSUE THREAD

**Issue by wch** [rstudio/profvis#84]
(This is related to #83.) For example, see http://rpubs.com/wch/294546

In the flame graph, you can see that there are seven time samples. All of the samples have `runif` on top of the call stack, as can be seen in the flame graph. In the data viewer, however, there are no entries for `runif`.

Here's the code. If you run it and there happens to be a `<GC>` above a `runif` in the flame graph, then the `runif` will show up in the data viewer (but the `<GC>` won't).

```R
profvis({
  fa <- function() {
    fb()
  }
  
  fb <- function() {
    runif(1e6)
  }

  fa()
  
  fb()
})
```

@javierluraschi Was this behavior intentional?

**Comment by javierluraschi** [comment]
@wch not intentional, from what I remember. BTW. Just noticed that switching between horizontal and vertical states is introducing jitter in the UI, not sure if this is already being tracked.
