### ISSUE TITLE
pandoc.exe: Out of memory

### ISSUE THREAD

**Issue by VT-SCM** [rstudio/profvis#89]
This issue has been asked but I'd like to have it emerged since it doesn't look like an uncommon issue. 
    profvis({runApp("Path_To_App", display.mode = "normal")})

The app takes a few hundred MB memory, but pandoc.exe takes more and more memory until a point it crashed due to the 2GB memory limit.

Is there a solution to this? Why does pandoc.exe take so much memory?
Thanks,
Victor

**Comment by wch** [comment]
The memory usage is probably due to jgm/pandoc#3169. I don't know of a workaround at this point.

**Comment by lionel-** [comment]
Duplicate of #67.
