### ISSUE TITLE
How do these numbers add up?

### ISSUE THREAD

**Issue by hadley** [rstudio/profvis#9]
![screen shot 2015-10-19 at 5 38 22 pm](https://cloud.githubusercontent.com/assets/4196/10593316/3f58c738-7688-11e5-9e27-e18cc9f8e4ea.png)

`extract()` takes 360 in total, but includes 330 + 160 + 110 ?

**Comment by wch** [comment]
Here's a simple example. It might be something weird with `lapply`:

```R
profvis(prof({
  f <- function(x) {
    x
  }
  lapply(1:100000, f)
}))
```

**Comment by wch** [comment]
I don't seem to see a problem here anymore. I suspect this was fixed when I stopped the double-counting of a given line.

This is what it looked like before:
![image](https://cloud.githubusercontent.com/assets/86978/15054740/95c6ded8-12ce-11e6-9d29-c67fa5091efd.png)

And now:
![image](https://cloud.githubusercontent.com/assets/86978/15054695/6542756a-12ce-11e6-9dac-aa742944b80a.png)
