### ISSUE TITLE
Profvis does not render when called with Rscript

### ISSUE THREAD

**Issue by dany-fu** [rstudio/profvis#95]
Hi, I have a script to profile and save to HTML that looks something like the following 

```
p <- profvis({
  function_to_profile()
})

htmlwidgets::saveWidget(p, "prof.html")
```

The flamegraph renders just fine when the script is sourced in RStudio `source("script.R")`
But I get a (Sources not available) error in the rendering when I do any of the following

from command line
`Rscript script.R`
`Rscript -e 'source("script.R")`

or even in RStudio
`system("Rscript script.R")`

I need to profile expensive operations on a server so it's important to be able to call the script from the command line

**Comment by wch** [comment]
https://rstudio.github.io/profvis/faq.html#how-do-i-get-source-code-to-show-with-rscript
